foodfresh/cart/urls.py
from django.conf.urls import url
from . import views
from django.contrib.auth.decorators import login_required

app_name = 'cart'
urlpatterns = [
    url(r'^add/$', views.CartAddView.as_view(), name='add'),
	url(r'^count/$', views.CartCountView.as_view(), name='count'),
	url(r'^info/$', login_required(views.CartInfoView.as_view()), name="info"),
	url(r'^update/$', views.CartUpdateView.as_view(), name='update'),
	url(r'^delete/$', views.CartDeleteView.as_view(), name='delete'),
    url(r'^get_cart_count/$', views.get_cart_count, name='get_cart_count'),
]

foodfresh/food/urls.py
from django.conf.urls import url
from . import views

app_name = 'food'
urlpatterns = [
    url(r'^index/$', views.IndexView.as_view(), name='index'),
    url(r'^detail/(?P<goods_id>\d+)/$', views.DetailView.as_view(), name='detail'),
    url(r'^list/(?P<type_id>\d+)/(?P<page>\d+)/$', views.ListView.as_view(), name='list'),
    url(r'^place_order/$', views.place_order),
]

foodfresh/foodfresh/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include

urlpatterns = [
    path('admin/', admin.site.urls),
    url('^user/', include('user.urls', namespace='user')),
    url('^food/', include('food.urls', namespace='food')),
	url('^cart/', include('cart.urls', namespace='cart')),
	url('^order/', include('order.urls', namespace='order')),
    url('^tinymce/', include('tinymce.urls')),
	url('^search/', include('haystack.urls')),
]

foodfresh/user/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required

from . import views

app_name = 'user'
urlpatterns = [
    url(r'^register/$', views.Register.as_view()),
    url(r'^active/(.*)/$', views.ActiveView.as_view()),
    url(r'^check_uname/$', views.check_uname),
    url(r'^login/$', views.LoginView.as_view()),
    url(r'^logout/$', views.LogoutView.as_view()),
    url(r'^user_response/$', views.user_response),
    url(r'^code_response/$', views.code_response),
    url(r'^verification_code/$', views.verification_code),
    url(r'^info/$', login_required(views.UserInfoView.as_view()), name='info'),
    url(r'^order/$', login_required(views.UserOrderView.as_view()), name='order'),
    url(r'^site/$', login_required(views.UserAddressView.as_view()), name='site'),
    url(r'^edit_site/(\d+)/$', login_required(views.EditAddressView.as_view()), name='edit_site'),
    url(r'^del_site/(\d+)$', views.del_site),
    url(r'^site_response/$', views.site_response),
    url(r'^pwd/$', login_required(views.ChangePwdView.as_view()), name='pwd'),
    url(r'^test/$', views.test),
]

foodfresh/cart/models.py
from django.db import models

foodfresh/user/models.py
from db.base_model import BaseModel
from django.contrib.auth.models import AbstractUser
from django.db import models

# Create your models here.


class UserInfo(AbstractUser, BaseModel):

    class Meta():
        db_table = 'user'
        verbose_name = '用户'
        verbose_name_plural = verbose_name


class EmailVerifyRecord(models.Model):
    # 激活码
    code = models.CharField(max_length=30)
    email = models.EmailField()
    # 邮件类型
    send_type = models.CharField(max_length=50)

    class Meta:
        db_table = 'emailverify'


class Address(BaseModel):
    '''地址模型类'''
    user = models.ForeignKey('UserInfo', verbose_name='所属用户', on_delete=True)
    receiver = models.CharField(max_length=20, verbose_name='收件人')
    addr = models.CharField(max_length=256, verbose_name='收件地址')
    zip_code = models.CharField(max_length=6, null=True, verbose_name='邮政编码')
    phone = models.CharField(max_length=11, verbose_name='联系电话')
    is_default = models.BooleanField(default=False, verbose_name='是否默认')

    class Meta:
        db_table = 'address'
        verbose_name = '地址'
        verbose_name_plural = verbose_name



foodfresh/cart/views.py
from django.shortcuts import render
from food.models import GoodsSKU
from django.conf import settings
from django.views.generic.base import View
from django.http import JsonResponse

# Create your views here.


class CartAddView(View):
	def post(self, request):
		user = request.user
		print(user)
		if not user.is_authenticated:
			return JsonResponse({'res': 0, 'errmsg': '请先登录'})

		sku_id = request.POST.get('sku_id')
		count = request.POST.get('count')
		
		if not all([sku_id, count]):
			return JsonResponse({'res': 1, 'errmsg': '数据不完整'})
		
		try:
			count = int(count)
		except Exception as e:
			return JsonResponse({'res': 2, 'errmsg': '商品数目出错了'})

		try:
			sku = GoodsSKU.objects.get(id=sku_id)
		except GoodsSKU.DoesNotExist:
			return JsonResponse({'res': 3, 'errmsg': '商品不存在'})

		conn = settings.REDIS_CONN
		cart_key = 'cart_%d' % user.id
		cart_count = conn.hget(cart_key, sku_id)
		if cart_count:
			count += int(cart_count)

		if count > sku.stock:
			return JsonResponse({'res': 4, 'errmsg': '商品库存不足'})
		
		conn.hset(cart_key, sku_id, count)
		total_count = get_cart_count(user)

		return JsonResponse({'res': 5, 'total_count': total_count, 'message': '添加成功'})


class CartCountView(View):
	def get(self, request):
		total_count = get_cart_count(request.user)
		return JsonResponse({'total_count':total_count})


class CartInfoView(View):
	def get(self, request):
		user = request.user
		conn = settings.REDIS_CONN
		cart_key = 'cart_%d' % user.id
		#{'商品id':商品数量,...}
		cart_dict = conn.hgetall(cart_key)
		print(cart_dict)

		skus = []
		#保存用户购物车中商品的总数目和总价格
		total_count = 0
		total_price = 0
		for sku_id, count in cart_dict.items():
			sku = GoodsSKU.objects.get(id=sku_id)
			amount = sku.price * int(count)
            #动态绑定总价属性、总数目属性
			sku.amount = amount
			sku.count = int(count)
			#添加到列表中
			skus.append(sku)

			#累加计算商品的总数目、总价格
			total_count += int(count)
			total_price += amount

		context = {
			'total_count': total_count,
			'total_price': total_price,
			'skus': skus,
			'title': '购物车'
		}

		return render(request, 'cart.html', context)


class CartUpdateView(View):
	def post(self, request):
		user = request.user
		if not user.is_authenticated:
			return JsonResponse({'res': 0, 'errmsg': '请先登录'})

		#获取数据
		sku_id = request.POST.get('sku_id')
		count = request.POST.get('count')
		print(count)

		#数据校验
		if not all([sku_id, count]):
			return JsonResponse({'res': 1, 'errmsg': '数据不完整'})

		try:
			count = int(count)
		except Exception as e:
			return JsonResponse({'res': 2, 'errmsg': '商品数目出错了'})

		try:
			sku = GoodsSKU.objects.get(id=sku_id)
		except GoodsSKU.DoesNotExist:
			return JsonResponse({'res': 3, 'errmsg': '商品不存在'})

		#更新
		conn = settings.REDIS_CONN
		cart_key = 'cart_%d' % user.id
		if count > sku.stock:
			return JsonResponse({'res': 4, 'errmsg': '商品库存不足'})
		
		conn.hset(cart_key, sku_id, count)
		total_count = get_cart_count(user)
		print(total_count)

		return JsonResponse({'res': 5, 'total_count': total_count, 'message': '更新成功'})


class CartDeleteView(View):
	def post(self, request):
		user = request.user
		if not user.is_authenticated:
			return JsonResponse({'res': 0, 'errmsg': '请先登录'})
	
		sku_id = request.POST.get('sku_id')

		if not sku_id:
			return JsonResponse({'res': 1, 'errmsg': '无效的商品id'})

		try:
			sku = GoodsSKU.objects.get(id=sku_id)
		except GoodsSKU.DoesNotExist:
			return JsonResponse({'res': 2, 'errmsg': '商品不存在'})

		conn = settings.REDIS_CONN
		cart_key = 'cart_%d' % user.id
		conn.hdel(cart_key, sku_id)	
	
		total_count = get_cart_count(user)

		return JsonResponse({'res': 3, 'total_count': total_count, 'message': '删除成功'})


def get_cart_count(user):
	total_count = 0
	if user.is_authenticated:
		conn = settings.REDIS_CONN
		cart_key = 'cart_%d' % user.id
		cart_dict = conn.hgetall(cart_key)\

		for sku_id, count in cart_dict.items():
			total_count += int(count)
	return total_count

foodfresh/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>天天生鲜-{{title}}</title>
    <link rel="stylesheet" type="text/css" href="/static/css/reset.css">
	<link rel="stylesheet" type="text/css" href="/static/css/main.css">
    <script type="text/javascript" src="/static/js/jquery-1.12.4.min.js"></script>
    {% block head %}{% endblock %}
</head>
<body>
{% block top%}{% endblock %}
{% block middle%}{% endblock %}
{% block bottom %}
<div class="footer">
    <div class="foot_link">
        <a href="#">关于我们</a>
        <span>|</span>
        <a href="#">联系我们</a>
        <span>|</span>
        <a href="#">招聘人才</a>
        <span>|</span>
        <a href="#">友情链接</a>
    </div>
    <p>CopyRight © 2016 北京天天生鲜信息技术有限公司 All Rights Reserved</p>
    <p>电话：010-****888    京ICP备*******8号</p>
</div>
{% endblock %}
</body>
</html>

foodfresh/templates/base_user.html
{% extends 'base.html' %}

foodfresh/templates/base_user_center.html
{% extends 'base_user.html' %}
{% block top %}
    <div class="header_con">
		<div class="header">
			<div class="welcome fl">欢迎来到天天生鲜!</div>
			<div class="fr">
				{% if user.is_authenticated  %}
                <div class="login_info fl">
                    欢迎您：<em>{{ user.username }}</em>
                    <span>|</span>
                    <a href="/user/logout">退出</a>
                    <span>|</span>
                </div>
		        {% else %}
		        <div class="login_btn fl">
		            <a href="/user/login">登录</a>
		            <span>|</span>
		            <a href="/user/register">注册</a>
		            <span>|</span>
		        </div>
		        {% endif %}
				<div class="user_link fl">
					<span>|</span>
					<a href="/user/info">用户中心</a>
					<span>|</span>
					<a href="/cart/info">我的购物车</a>
					<span>|</span>
					<a href="/user/order">我的订单</a>
				</div>
			</div>
		</div>
	</div>
	
	
	<div class="search_bar clearfix">
		<a href="index.html" class="logo fl"><img src="/static/images/logo.png"></a>
		<div class="sub_page_name fl">|&nbsp;&nbsp;&nbsp;&nbsp;{{ title }}</div>
		<div class="search_con fr">
			<input type="text" class="input_text fl" name="" placeholder="搜索商品">
			<input type="button" class="input_btn fr" name="" value="搜索">
		</div>
	</div>
	
{% endblock %}
{% block middle %}
<div class="main_con clearfix">
		{% block left %}
		<div class="left_menu_con clearfix">
			<h3>用户中心</h3>
			<ul>
				<li><a href="{% url 'user:info' %}" {% if page == 'info' %}class="active"{% endif %}>· 个人信息</a></li>
				<li><a href="{% url 'user:pwd' %}" {% if page == 'pwd' %}class="active"{% endif %}>· 修改密码</a></li>
				<li><a href="{% url 'user:order' %}" {% if page == 'order' %}class="active"{% endif %}>· 全部订单</a></li>
				<li><a href="{% url 'user:site' %}" {% if page == 'site' %}class="active"{% endif %}>· 收货地址</a></li>
			</ul>
		</div>
		{% endblock %}
        {% block right %}{% endblock %}
</div>
{% endblock %}

foodfresh/templates/detail.html
{% extends 'base_goods.html' %}
{% block middle %}
	<div class="navbar_con">
		<div class="navbar clearfix">
			<div class="subnav_con fl">
				<h1>全部商品分类</h1>	
				<span></span>			
				<ul class="subnav">
					<li><a href="#" class="fruit">新鲜水果</a></li>
					<li><a href="#" class="seafood">海鲜水产</a></li>
					<li><a href="#" class="meet">猪牛羊肉</a></li>
					<li><a href="#" class="egg">禽类蛋品</a></li>
					<li><a href="#" class="vegetables">新鲜蔬菜</a></li>
					<li><a href="#" class="ice">速冻食品</a></li>
				</ul>
			</div>
			<ul class="navlist fl">
				<li><a href="{% url 'food:index' %}">首页</a></li>
				<li class="interval">|</li>
				<li><a href="">手机生鲜</a></li>
				<li class="interval">|</li>
				<li><a href="">抽奖</a></li>
			</ul>
		</div>
	</div>

	<div class="breadcrumb">
		<a href="#">全部分类</a>
		<span>></span>
		<a href="#">新鲜水果</a>
		<span>></span>
		<a href="#">商品详情</a>
	</div>

	<div class="goods_detail_con clearfix">
		<div class="goods_detail_pic fl"><img src="{{ sku.image.url }}"></div>

		<div class="goods_detail_list fr">
			<h3>{{ sku.name }}</h3>
			<p>{{ sku.desc }}</p>
			<div class="prize_bar">
				<span class="show_pirze">¥<em>{{ sku.price|floatformat:2 }}</em></span>
				<span class="show_unit">单  位：{{ sku.unite }}</span>
				<span class="show_stock">库存：{{ sku.stock }}--销量：{{ sku.sales }}</span>
			</div>
			<div class="goods_num clearfix">
				<div class="num_name fl">数 量：</div>
				<div class="num_add fl">
					<input type="text" class="num_show fl" value="1">
					<a href="javascript:;" class="add fr">+</a>
					<a href="javascript:;" class="minus fr">-</a>	
				</div> 
			</div>
			<div class="total">总价：<em>{{ sku.price|floatformat:2 }}</em></div>
			<div class="operate_btn">
				{% csrf_token %}
				<a href="javascript:;" class="buy_btn">立即购买</a>
				<a href="javascript:;" sku_id="{{ sku.id }}" class="add_cart" id="add_cart">加入购物车</a>				
			</div>
		</div>
	</div>

	<div class="main_wrap clearfix">
		<div class="l_wrap fl clearfix">
			<div class="new_goods">
				<h3>新品推荐</h3>
				<ul>
                {% for sku in new_skus %}
					<li>
						<a href="{% url 'food:detail' sku.id %}"><img src="{{ sku.image.url }}"></a>
						<h4><a href="{% url 'food:detail' sku.id %}">{{ sku.name }}</a></h4>
						<div class="prize">￥{{ sku.price|floatformat:2 }}</div>
					</li>
                {% empty %}
					无
				{% endfor %}
				</ul>
			</div>
		</div>

		<div class="r_wrap fr clearfix">
			<ul class="detail_tab clearfix">
				<li id="tag_detail" class="active">商品介绍</li>
				<li id="tag_comment">评论</li>
			</ul>

			<div class="tab_content">
				<dl>
					<dt>商品详情：</dt>
					<dd>{{ sku.goods.detail }} </dd>
				</dl>
			</div>
            
			<div class="tab_comment" style="display:none;">
				<dl>
					<dt>评论：</dt>
					<dd></dd>
				</dl>
			</div>
		</div>
	</div>
	<div class="add_jump"></div>
	<script type="text/javascript" src="/static/js/jquery-1.12.4.min.js"></script>
	<script type="text/javascript">
		$(function(){
			//获取商品数量
			var num = parseInt($('.num_show').val())
			//获取商品单价
			var price = parseFloat($('.show_pirze').children('em').eq(0).text())
			$('.add').click(function(){
				num = num + 1
				if(num > {{ sku.stock }}){
					num = {{ sku.stock }}
				}
				$('.num_show').val(num)
				total()
			})

			$('.minus').click(function(){
				if(num>1){
					num = num -1
				}else{
					num = 1
				}
				$('.num_show').val(num)
				total()

			})
			
			function total(){
				//获取商品数量
				var num = parseInt($('.num_show').val())
				//获取商品单价
				var price = parseFloat($('.show_pirze').children('em').eq(0).text())
				//计算总价
				var total = num*price
				$('.total').children('em').eq(0).text(total.toFixed(2))
			}

		    //手动输入商品数量
			$('.num_show').blur(function(){
				//获取用户输入的数量
				num = $(this).val()
		        //校验count是否合法
		  		if(isNaN(num) || num.trim().length == 0 || parseInt(num) <= 0){
					num = 1
				}
				$(this).val(parseInt(num))
				total()
			})		


		    //商品介绍和评论的div切换
		    $('#tag_detail').click(function(){
				$(this).addClass('active')
		        $('#tag_comment').removeClass('active')
		        $('.tab_content').css('display', 'block')
				$('.tab_comment').css('display', 'none')
			})	

			$('#tag_comment').click(function(){
				$(this).addClass('active')
				$('#tag_detail').removeClass('active')
				$('.tab_comment').css('display', 'block')
				$('.tab_content').css('display', 'none')
			})	
		
			var $add_x = $('#add_cart').offset().top;
			var $add_y = $('#add_cart').offset().left;

			var $to_x = $('#show_count').offset().top;
			var $to_y = $('#show_count').offset().left;

			$('#add_cart').click(function(){
				//获取商品id和商品数量
				sku_id = $(this).attr('sku_id')
				count = $('.num_show').val()
				csrf = $('input[name="csrfmiddlewaretoken"]').val()
				params = {'sku_id': sku_id, 'count': count, 'csrfmiddlewaretoken': csrf}
				$.post('/cart/add/', params, function(data){
					if(data.res == 5){
						$('.add_jump').css({'left': $add_y + 80, 'top': $add_x + 10, 'display': 'block'})
						$('.add_jump').stop().animate({
							'left': $to_y + 7,
							'top': $to_x + 7
						},
						'slow', function(){
							$('.add_jump').fadeOut('fast', function(){
								$('#show_count').html(data.total_count);
							});
						});
					}
					else if(data.res == 0){
						alert(data.errmsg)
					}
				})
			})

		})
	    
	</script>
	
{% endblock %}

foodfresh/templates/index.html
{% extends 'base_goods.html' %}
{% block head %}
	<script type="text/javascript" src="/static/js/jquery-ui.min.js"></script>
	<script type="text/javascript" src="/static/js/slide.js"></script>
{% endblock %}
{% block middle %}
	<div class="navbar_con">
		<div class="navbar">
			<h1 class="fl">全部商品分类</h1>
			<ul class="navlist fl">
				<li><a href="{% url 'food:index' %}">首页</a></li>
				<li class="interval">|</li>
				<li><a href="">手机生鲜</a></li>
				<li class="interval">|</li>
				<li><a href="">抽奖</a></li>
			</ul>
		</div>
	</div>

	<div class="center_con clearfix">
		<ul class="subnav fl">
		{% for type in types %}
			<li><a href="#model0{{forloop.counter}}" class="{{type.logo}}">{{type.name}}</a></li>
		{% endfor %}
		</ul>
		<div class="slide fl">
			<ul class="slide_pics">
			{% for good in good_banners %}
				<li><img src="{{ good.image.url }}" alt="幻灯片"></li>
            {% endfor %}
			</ul>
			<div class="prev"></div>
			<div class="next"></div>
			<ul class="points"></ul>
		</div>
		<div class="adv fl">
			{% for promotion in promotion_banners %}
			<a href="#"><img src="{{ promotion.image.url }}"></a>
			{% endfor %}
		</div>
	</div>
	
	{% for type in types %}
	<div class="list_model">
		<div class="list_title clearfix">
			<h3 class="fl" id="model01">{{ type.name }}</h3>
			<div class="subtitle fl">
				<span>|</span>
				{% for title_banner in type.title_banners %}
				<a href="{% url 'food:detail' title_banner.sku.id %}">{{ title.sku.name }}</a>
				{% endfor %}
			</div>
			<a href="{% url 'food:list' type.id 1 %}?sort={{ sort }}" class="goods_more fr" id="fruit_more">查看更多 ></a>
		</div>

		<div class="goods_con clearfix">
			<div class="goods_banner fl"><img src="{{ type.image.url }}"></div>
			<ul class="goods_list fl">
				{% for image_banner in type.image_banners %}
				<li>
					<h4><a href="{% url 'food:detail' image_banner.sku.id %}">{{ image_banner.sku.name }}</a></h4>
					<a href="{% url 'food:detail' image_banner.sku.id %}"><img src="{{ image_banner.sku.image.url }}"></a>
					<div class="prize">￥{{ image_banner.sku.price|floatformat:2 }}</div>
				</li>
				{% endfor %}
			</ul>
		</div>
	</div>
	{% endfor %}
{% endblock %}

foodfresh/templates/list.html
{% extends 'base_goods.html' %}
{% block middle %}
	<div class="navbar_con">
		<div class="navbar clearfix">
			<div class="subnav_con fl">
				<h1>全部商品分类</h1>	
				<span></span>			
				<ul class="subnav">
					<li><a href="#" class="fruit">新鲜水果</a></li>
					<li><a href="#" class="seafood">海鲜水产</a></li>
					<li><a href="#" class="meet">猪牛羊肉</a></li>
					<li><a href="#" class="egg">禽类蛋品</a></li>
					<li><a href="#" class="vegetables">新鲜蔬菜</a></li>
					<li><a href="#" class="ice">速冻食品</a></li>
				</ul>
			</div>
			<ul class="navlist fl">
				<li><a href="">首页</a></li>
				<li class="interval">|</li>
				<li><a href="">手机生鲜</a></li>
				<li class="interval">|</li>
				<li><a href="">抽奖</a></li>
			</ul>
		</div>
	</div>

	<div class="breadcrumb">
		<a href="#">全部分类</a>
		<span>></span>
		<a href="#">{{ type.name }}</a>
	</div>

	<div class="main_wrap clearfix">
		<div class="l_wrap fl clearfix">
			<div class="new_goods">
				<h3>新品推荐</h3>
				<ul>
                {% for sku in new_skus %}
					<li>
						<a href="#"><img src="{{ sku.image.url }}"></a>
						<h4><a href="#">{{ sku.name }}</a></h4>
						<div class="prize">{{ sku.price }}</div>
					</li>
                {% empty %}
                	无
                {% endfor %}
				</ul>
			</div>
		</div>

		<div class="r_wrap fr clearfix">
			<div class="sort_bar">
				<a href="{% url 'food:list' type.id 1 %}" {% if sort == 'default' %}class="active"{% endif %}>默认</a>
				<a href="{% url 'food:list' type.id 1 %}" {% if sort == 'price' %}class="active"{% endif %}>价格</a>
				<a href="{% url 'food:list' type.id 1 %}" {% if sort == 'sales' %}class="active"{% endif %}>人气</a>
			</div>

			<ul class="goods_type_list clearfix">
                {% for sku in sku_page.object_list %}
				<li>
					<a href="{% url 'food:detail' sku.id %}"><img src="{{ sku.image.url }}"></a>
					<h4><a href="{% url 'food:detail' sku.id %}">{{ sku.name }}</a></h4>
					<div class="operate">
						<span class="prize">{{ sku.price }}</span>
						<span class="unit">{{ sku.unite }}</span>
						<a href="#" class="add_goods" title="加入购物车"></a>
					</div>
				</li>
                {% endfor %}
			</ul>

			<div class="pagenation">
                {% if sku_page.has_previous %}
					<a href="{% url 'food:list' type.id sku_page.previous_page_number %}?sort={{ sort }}"><上一页</a>
				{% endif %}
                {% for pindex in pages %}
					{% if pindex == sku_page.number %}
						<a href="{% url 'food:list' type.id pindex %}?sort={{ sort }}" class="active">{{ pindex }}</a>
                    {% else %}
                        <a href="{% url 'food:list' type.id pindex %}?sort={{ sort }}">{{ pindex }}</a>
					{% endif %}
                {% endfor %}
				{% if sku_page.has_next %}
					<a href="{% url 'food:list' type.id sku_page.next_page_number %}?sort={{ sort }}">下一页></a>
				{% endif %}
			</div>
		</div>
	</div>
{% endblock %}

foodfresh/templates/place_order.html
{% extends 'base_user_center.html' %}
{% block middle %}
	{% block left %}{% endblock %}
	<h3 class="common_title">确认收货地址</h3>

	<div class="common_list_con clearfix">
		<dl>
			<dt>寄送到：</dt>
			{% for addr in addrs %}
				{% if addr.is_default %}
					<dd><input type="radio" name="" checked>{{ addr.addr }} （{{ addr.receiver }} 收） {{ addr.phone }}</dd>
				{% else %}
					<dd><input type="radio" name="">{{ addr.addr }} （{{ addr.receiver }} 收） {{ addr.phone }}</dd>
				{% endif %}
			{% empty %}
				无
			{% endfor %}
		</dl>
		<a href="{% url 'user:site' %}" class="edit_site">编辑收货地址</a>

	</div>
	
	<h3 class="common_title">支付方式</h3>	
	<div class="common_list_con clearfix">
		<div class="pay_style_con clearfix">
			<input type="radio" name="pay_style" checked>
			<label class="cash">货到付款</label>
			<input type="radio" name="pay_style">
			<label class="weixin">微信支付</label>
			<input type="radio" name="pay_style">
			<label class="zhifubao"></label>
			<input type="radio" name="pay_style">
			<label class="bank">银行卡支付</label>
		</div>
	</div>

	<h3 class="common_title">商品列表</h3>
	
	<div class="common_list_con clearfix">
		<ul class="goods_list_th clearfix">
			<li class="col01">商品名称</li>
			<li class="col02">商品单位</li>
			<li class="col03">商品价格</li>
			<li class="col04">数量</li>
			<li class="col05">小计</li>		
		</ul>
		{% for sku in skus %}
		<ul class="goods_list_td clearfix">
			<li class="col01">{{ forloop.counter }}</li>			
			<li class="col02"><img src="{{ sku.image.url }}"></li>
			<li class="col03">{{ sku.name }}</li>
			<li class="col04">{{ sku.unite }}</li>
			<li class="col05">{{ sku.price }}</li>
			<li class="col06">{{ sku.count }}</li>
			<li class="col07">{{ sku.amount }}</li>	
		</ul>
		{% empty %}
			无
		{% endfor %}
	</div>

	<h3 class="common_title">总金额结算</h3>

	<div class="common_list_con clearfix">
		<div class="settle_con">
			<div class="total_goods_count">共<em>{{ total_count }}</em>件商品，总金额<b>{{ total_price }}</b></div>
			<div class="transit">运费：<b>{{ transit_price }}</b></div>
			<div class="total_pay">实付款：<b>{{ total_pay }}</b></div>
		</div>
	</div>

	<div class="order_submit clearfix">
		<a href="javascript:;" id="order_btn">提交订单</a>
	</div>	

	<div class="popup_con">
		<div class="popup">
			<p>订单提交成功！</p>
		</div>
		
		<div class="mask"></div>
	</div>
	<script type="text/javascript" src="/static/js/jquery-1.12.2.js"></script>
	<script type="text/javascript">
		$('#order_btn').click(function() {
			localStorage.setItem('order_finish',2);

			$('.popup_con').fadeIn('fast', function() {

				setTimeout(function(){
					$('.popup_con').fadeOut('fast',function(){
						window.location.href = 'index.html';
					});	
				},3000)
				
			});
		});
	</script>
{% endblock %}

foodfresh/templates/user_center_info.html
{% extends 'base_user_center.html' %}
{% block right %}
	<div class="right_content clearfix">
				<div class="info_con clearfix">
				<h3 class="common_title2">基本信息</h3>
						<ul class="user_info_list">
							<li><span>用户名：</span>{{request.user.username}}</li>
							<li><span>联系方式：</span></li>
							<li><span>联系地址：</span></li>
						</ul>
				</div>

				<h3 class="common_title2">最近浏览</h3>
				<div class="has_view_list">
					<ul class="goods_type_list clearfix">
		            {% for goods in goods_li %}
						<li>
							<a href="{% url 'food:detail' goods.id %}"><img src="{{ goods.image.url }}"></a>
							<h4><a href="{% url 'food:index' %}">{{ goods.name }}</a></h4>
							<div class="operate">
								<span class="prize">{{ goods.price }}</span>
								<span class="unit">{{ goods.unite }}</span>
								<a href="#" class="add_goods" title="加入购物车"></a>
							</div>
						</li>
					{% empty %}
						无
					{% endfor %}
					</ul>
		</div>
		</div>
{% endblock %}

